### PR TITLE
Add pyproject.toml and some more customizable parameters

### PR DESCRIPTION
**Pull request by nielstron**

### CODE REVIEW

**Comment by timyerg** [comment]
Hello!
Thank you for contributing to the project.
I see you added some parameters that were default and some fixes to the code. Did you test all the functionality?
To be honest, I am not very comfortable with Github and am not sure what to do now.
I guess, after testing it should be:

- merge pull request
- update pip version

Is that correct?

**Comment by nielstron** [comment]
Hey, yes that's correct. I ran the code locally and produced some figures from it using i.e. edge_color = None. To be sure that I did not introduce anything specific to my setup/platform it would be good if you run the code yourself as well.
You can for example
```
# if you already have clone of the repo run in its root
git remote add nielstron https://github.com/nielstron/venny4py.git
git fetch nielstron
git checkout nielstron/main
# otherwise run
git clone https://github.com/nielstron/venny4py.git
cd venny4py

# run whatever code you ran before to test that everything works to your satisfaction
...
```

If you agree with everything, hit merge, update the version number in pyproject.toml and upload the new version to pypi :)

**Comment by timyerg** [comment]
Great, thank you for the instructions.
I will try to merge it after testing.

**Comment by timyerg** [comment]
Looks like it worked.

Thank you again for providing additional parameters that had default values only and your help with merging.

**Pull request merged**
